test:	uah_employee.o uah_person.o uah_person_driver.o uah_student.o
	g++ uah_employee.o uah_person.o uah_person_driver.o uah_student.o -o test
uah_person_driver.o:    uah_person_driver.cpp
	g++ -c uah_person_driver.cpp 
uah_employee.o:	uah_employee.cpp
	g++ -c uah_employee.cpp
uah_person.o:	uah_person.cpp
	g++ -c uah_person.cpp 
uah_student.o:  uah_student.cpp
	g++ -c uah_student.cpp


