exam1:	uah_employee.o uah_person.o uah_person_driver.o uah_student.o uah_ta.o
	g++ uah_employee.o uah_person.o uah_person_driver.o uah_student.o uah_ta.o -o exam1
uah_person_driver.o:    uah_person_driver.cpp
	g++ -c uah_person_driver.cpp 
uah_employee.o:	uah_employee.cpp
	g++ -c uah_employee.cpp
uah_person.o:	uah_person.cpp
	g++ -c uah_person.cpp 
uah_student.o:  uah_student.cpp
	g++ -c uah_student.cpp
uah_ta.o: uah_ta.cpp
	g++ -c uah_ta.cpp


